app:
  name: "watchdog"
  mode: "dev"
  port: 8081
  version: "v0.0.4"
  start_time: "2020-07-01"
  machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "watchdog.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "192.168.31.17"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "sql_test"
  max_open_conns: 200
  max_idle_conns: 10

redis:
  host: "192.168.31.17"
  port: 6379
  password: ""
  db: 0
  pool_size: 100